### ISSUE TITLE
Can't add API key to OpenAI

### ISSUE THREAD

**Issue by pitredish** [chathub-dev/chathub#1302]
**Describe the bug**
Under OpenAI, when I click Configure under "Use your own API key" I get the following error: 

Unexpected Application Error!
Cannot read properties of undefined (reading 'name')
TypeError: Cannot read properties of undefined (reading 'name')
    at chrome-extension://iaakpnchhognanibcahlpcplchdfmgma/assets/premium-54ab6b19.js:390:63456
    at Object.useMemo (chrome-extension://iaakpnchhognanibcahlpcplchdfmgma/assets/premium-54ab6b19.js:39:23365)
    at rn.useMemo (chrome-extension://iaakpnchhognanibcahlpcplchdfmgma/assets/premium-54ab6b19.js:9:6253)
    at kkt (chrome-extension://iaakpnchhognanibcahlpcplchdfmgma/assets/premium-54ab6b19.js:390:63422)
    at E8 (chrome-extension://iaakpnchhognanibcahlpcplchdfmgma/assets/premium-54ab6b19.js:39:17030)
    at QH (chrome-extension://iaakpnchhognanibcahlpcplchdfmgma/assets/premium-54ab6b19.js:41:44079)
    at YH (chrome-extension://iaakpnchhognanibcahlpcplchdfmgma/assets/premium-54ab6b19.js:41:39797)
    at Sce (chrome-extension://iaakpnchhognanibcahlpcplchdfmgma/assets/premium-54ab6b19.js:41:39723)
    at lb (chrome-extension://iaakpnchhognanibcahlpcplchdfmgma/assets/premium-54ab6b19.js:41:39574)
    at E7 (chrome-extension://iaakpnchhognanibcahlpcplchdfmgma/assets/premium-54ab6b19.js:41:35937)
    at JP (chrome-extension://iaakpnchhognanibcahlpcplchdfmgma/assets/premium-54ab6b19.js:41:36742)
    at xc (chrome-extension://iaakpnchhognanibcahlpcplchdfmgma/assets/premium-54ab6b19.js:39:3288)
    at chrome-extension://iaakpnchhognanibcahlpcplchdfmgma/assets/premium-54ab6b19.js:41:34264

**Desktop (please complete the following information):**
 - OS: MacOS Sequoia 15.0.1
 - Browser Edge
 - ChatHub Version: v3.49.3

**Comment by wong2** [comment]
Can you try to re-install the extension?

**Comment by pitredish** [comment]
That did it. Thanks!

**Comment by pitredish** [comment]
That did it. Thanks!
